apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-config
data:
  # Database Configuration
  POSTGRES_HOST: "circleguard-postgres"
  POSTGRES_PORT: "5432"
  
  # Neo4j Configuration
  NEO4J_URI: "bolt://circleguard-neo4j:7687"
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "circleguard-kafka:9092"
  
  # Redis Configuration
  REDIS_HOST: "circleguard-redis"
  REDIS_PORT: "6379"
