apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: circleguard/identity-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: circleguard-config
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service

spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
